In [1]:
import qutip
from qutip.qip.operations import cnot, rx, ry, rz
import numpy as np
from qiskit.visualization import array_to_latex

In [17]:

proj1 = qutip.basis(4,0)*qutip.basis(4,0).dag() + qutip.basis(4,1)*qutip.basis(4,1).dag()
proj2 = qutip.basis(4,2)*qutip.basis(4,2).dag()+qutip.basis(4,3)*qutip.basis(4,3).dag()

array_to_latex(*proj2)

<IPython.core.display.Latex object>

In [19]:
array_to_latex((qutip.basis(4,0)*qutip.basis(4,0).dag())*rz(np.pi/2))

TypeError: Incompatible Qobj shapes

In [53]:
u1 = qutip.tensor(ry(np.pi/2), qutip.qeye(2))
u2 = rzz3
u3 = qutip.tensor(rx(np.pi/2), ry(np.pi/2))
u4 = rzz3
u5 = qutip.tensor(qutip.qeye(2), rx(np.pi/2))
temp = u5*u4*u3*u2*u1
array_to_latex(temp)

<IPython.core.display.Latex object>

In [47]:
array_to_latex(P1)

<IPython.core.display.Latex object>

In [2]:
rzz = qutip.Qobj(np.array([[np.exp(1j*np.pi/4),0,0,0],[0, np.exp(-1j*np.pi/4),0,0],[0,0,np.exp(-1j*np.pi/4),0],[0,0,0,np.exp(1j*np.pi/4)]]), dims=[[2,2],[2,2]])
rzz3 = qutip.Qobj(np.array([[np.exp(3*1j*np.pi/4),0,0,0],[0, np.exp(3*-1j*np.pi/4),0,0],[0,0,np.exp(3*-1j*np.pi/4),0],[0,0,0,np.exp(3*1j*np.pi/4)]]), dims=[[2,2],[2,2]])


u1 = qutip.tensor(qutip.qeye(2), ry(np.pi/4))
u2 = qutip.tensor(qutip.qeye(2), rx(np.pi))
u3 = qutip.tensor(qutip.qeye(2), ry(-np.pi/4))
u4 = qutip.tensor(rz(np.pi/2), qutip.qeye(2))
u5 = qutip.tensor(qutip.qeye(2), rz(np.pi/2))
u6 = rzz
u7 = qutip.tensor(qutip.qeye(2), ry(np.pi/4))
u8 = qutip.tensor(qutip.qeye(2), rx(np.pi))
u9 = qutip.tensor(qutip.qeye(2), ry(-np.pi/4))
gp_cnot = u9*u8*u7*u6*u5*u4*u3*u2*u1
array_to_latex(gp_cnot)

<IPython.core.display.Latex object>

In [32]:
array_to_latex(rz(-1*np.pi/2))

<IPython.core.display.Latex object>

In [29]:
array_to_latex(rzz)

<IPython.core.display.Latex object>

In [82]:
# attempting their p1 sequence
u1 = qutip.tensor(rx(np.pi/2), qutip.qeye(2))
u2 = rzz
u3 = qutip.tensor(ry(np.pi/2), rx(np.pi/2))
u4 = rzz
u5 = qutip.tensor(qutip.qeye(2), ry(np.pi/2))
p1_pulse = (u5*u4*u3*u2*u1)
p1_pulse_d = p1_pulse.dag()
array_to_latex(qutip.Qobj(p1_pulse.data*v.data*p1_pulse_d.data))

<IPython.core.display.Latex object>

In [83]:
# attempting their p2 sequence
u1 = qutip.tensor(qutip.qeye(2),rx(np.pi/2))
u2 = rzz
u3 = qutip.tensor(rx(np.pi/2), ry(np.pi/2))
u4 = rzz
u5 = qutip.tensor(ry(np.pi/2), qutip.qeye(2))
p2_pulse = (u5*u4*u3*u2*u1)
p2_pulse_d = p2_pulse.dag()
array_to_latex(qutip.Qobj(p2_pulse.data*v.data*p2_pulse_d.data))

<IPython.core.display.Latex object>

In [3]:
P1 = (cnot(2,control=0,target=1)*cnot(2,control=1,target=0))
P1d = P1.dag()
P2 = (cnot(2,control=1,target=0)*cnot(2,control=0,target=1))
P2d = P2.dag()
v = qutip.Qobj([[5,0,0,0],[0,3,0,0],[0,0,-3,0],[0,0,0,-5]])
cn = cnot(2,0,1)

In [44]:
array_to_latex(qutip.Qobj(P1.data*v.data*P1d.data))

<IPython.core.display.Latex object>

In [84]:
# P1 00
P1 = (cnot(2,control=0,target=1)*cnot(2,control=1,target=0))
P1d = P1.dag()
p1_00 = qutip.Qobj(cn*P1.data*v.data*P1d.data*cn)
print(p1_00)
print("Carbon peaks at {}, {}".format((p1_00[2][0][2]-p1_00[3][0][3]), (p1_00[0][0][0]-p1_00[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 5.  0.  0.  0.]
 [ 0. -5.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  3.]]
Carbon peaks at (-6+0j), (10+0j)


In [85]:
# P2 00
P2 = (cnot(2,control=1,target=0)*cnot(2,control=0,target=1))
P2d = P2.dag()
p2_00 = qutip.Qobj(cn*P2.data*v.data*P2d.data*cn)
print(p2_00)
print("Carbon peaks at {}, {}".format((p2_00[2][0][2]-p2_00[3][0][3]), (p2_00[0][0][0]-p2_00[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 5.  0.  0.  0.]
 [ 0. -3.  0.  0.]
 [ 0.  0.  3.  0.]
 [ 0.  0.  0. -5.]]
Carbon peaks at (8+0j), (8+0j)


In [86]:
# P1 01
P1 = qutip.tensor(rx(np.pi),rx(np.pi))*(cnot(2,control=0,target=1)*cnot(2,control=1,target=0))
P1d = P1.dag()
p1_01 = qutip.Qobj(cn*P1.data*v.data*P1d.data*cn)
print(p1_01)
print("Carbon peaks at {}, {}".format((p1_01[2][0][2]-p1_01[3][0][3]), (p1_01[0][0][0]-p1_01[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-3.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0.  5.  0.]
 [ 0.  0.  0. -5.]]
Carbon peaks at (10+0j), (-6+0j)


In [87]:
# P2 01
P2 = qutip.tensor(rx(np.pi),qutip.qeye(2))*(cnot(2,control=1,target=0)*cnot(2,control=0,target=1))
P2d = P2.dag()
p2_01 = qutip.Qobj(cn*P2.data*v.data*P2d.data*cn)
print(p2_01)
print("Carbon peaks at {}, {}".format((p2_01[2][0][2]-p2_01[3][0][3]), (p2_01[0][0][0]-p2_01[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-5.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0.  5.]]
Carbon peaks at (-8+0j), (-8+0j)


In [88]:
# P1 10
P1 = qutip.tensor(qutip.qeye(2),rx(np.pi))*(cnot(2,control=0,target=1)*cnot(2,control=1,target=0))
P1d = P1.dag()
p1_10 = qutip.Qobj(cn.data*P1.data*v.data*P1d.data*cn.data)
print(p1_10)
print("Carbon peaks at {}, {}".format((p1_10[2][0][2]-p1_10[3][0][3]), (p1_10[0][0][0]-p1_10[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-5.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0.  3.  0.]
 [ 0.  0.  0. -3.]]
Carbon peaks at (6+0j), (-10+0j)


In [89]:
# P2 10
P2 = qutip.tensor(rx(np.pi),rx(np.pi))*(cnot(2,control=1,target=0)*cnot(2,control=0,target=1))
P2d = P2.dag()
p2_10 = qutip.Qobj(cn*P2.data*v.data*P2d.data*cn)
print(p2_10)
print("Carbon peaks at {}, {}".format((p2_10[2][0][2]-p2_10[3][0][3]), (p2_10[0][0][0]-p2_10[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 3.  0.  0.  0.]
 [ 0. -5.  0.  0.]
 [ 0.  0.  5.  0.]
 [ 0.  0.  0. -3.]]
Carbon peaks at (8+0j), (8+0j)


In [90]:
# P1 11
P1 = qutip.tensor(rx(np.pi),qutip.qeye(2))*(cnot(2,control=0,target=1)*cnot(2,control=1,target=0))
P1d = P1.dag()
p1_11 = qutip.Qobj(cn*P1.data*v.data*P1d.data*cn)
print(p1_11)
print("Carbon peaks at {}, {}".format((p1_11[2][0][2]-p1_11[3][0][3]), (p1_11[0][0][0]-p1_11[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 3.  0.  0.  0.]
 [ 0. -3.  0.  0.]
 [ 0.  0. -5.  0.]
 [ 0.  0.  0.  5.]]
Carbon peaks at (-10+0j), (6+0j)


In [91]:
# P2 11
P2 = qutip.tensor(qutip.qeye(2),rx(np.pi))*(cnot(2,control=1,target=0)*cnot(2,control=0,target=1))
P2d = P2.dag()
p2_11 = qutip.Qobj(cn*P2.data*v.data*P2d.data*cn)
print(p2_11)
print("Carbon peaks at {}, {}".format((p2_11[2][0][2]-p2_11[3][0][3]), (p2_11[0][0][0]-p2_11[1][0][1])))

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-3.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0. -5.  0.]
 [ 0.  0.  0.  3.]]
Carbon peaks at (-8+0j), (-8+0j)


In [92]:
p_00_avg = (1/3)*(v+p1_00+p2_00)
p_01_avg = (1/3)*(v+p1_01+p2_01)
p_10_avg = (1/3)*(v+p1_10+p2_10)
p_11_avg = (1/3)*(v+p1_11+p2_11)
print(p_00_avg)
print(p_01_avg)
print(p_10_avg)
print(p_11_avg)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 5.          0.          0.          0.        ]
 [ 0.         -1.66666667  0.          0.        ]
 [ 0.          0.         -1.          0.        ]
 [ 0.          0.          0.         -2.33333333]]
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-1.          0.          0.          0.        ]
 [ 0.          3.          0.          0.        ]
 [ 0.          0.         -0.33333333  0.        ]
 [ 0.          0.          0.         -1.66666667]]
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          1.66666667  0.        ]
 [ 0.          0.          0.         -3.66666667]]
Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.66666667  0.        

In [101]:
# p1

# 90x H
u2 = qutip.tensor(rx(np.pi/2), qutip.qeye(2))
# rzz
u3 = rzz
# ry rx
u4 = qutip.tensor(ry(np.pi/2), rx(np.pi/2))
# rzz
u5 = rzz
# y C 90
u6 = qutip.tensor(qutip.qeye(2), ry(np.pi/2))
temp = u6*u5*u4*u3*u2
tempd = temp.dag()
array_to_latex(qutip.Qobj(temp.data*v.data*tempd.data))
#array_to_latex(temp)

<IPython.core.display.Latex object>

In [98]:
array_to_latex(qutip.Qobj(P1.data*v.data*P1d.data))

<IPython.core.display.Latex object>

In [99]:
array_to_latex(qutip.Qobj(P2.data*v.data*P2d.data))

<IPython.core.display.Latex object>

In [ ]:
u1 = qutip.tensor(qutip.qeye(2), ry(-np.pi/2))
u2 = qutip.tensor()
